//===----------------------------------------------------------------------===//
//
// This source file is part of the MCP open source project
//
// Copyright (c) 2024 and the MCP project authors
// Licensed under the MIT License
//
// See LICENSE.txt for license information
//
//===----------------------------------------------------------------------===//

import Logging
import QuickJSON

/// A tool binary's self-description: its identity plus the compiled tool
/// surface, as data.
///
/// The catalog is built by ``discover(name:version:description:dispatcher:additionalTools:)``
/// from the **same router catalog** that `tools/list` serializes on the live
/// wire, so a binary's introspection output (`--mcp-list`, manifest emission)
/// and its session behavior cannot drift.
///
/// Encoding is canonical: object keys are sorted at every depth. Swift's
/// dictionary iteration order varies between processes (per-process hash
/// seeds), so a catalog encoded straight from dictionaries would not be
/// byte-stable across runs — sorted keys make introspection output
/// deterministic and diffable.
public struct MCPToolCatalog: Codable, Sendable, Equatable {
    /// One tool in the catalog.
    public struct Tool: Codable, Sendable, Equatable {
        /// The registered tool name (the key used by `tools/call`).
        public let name: String
        /// The human-readable tool description, when it has one.
        public let description: String?
        /// The tool's JSON Schema parameters object — the same
        /// `inputSchema` shape that `tools/list` serves on the wire.
        public let inputSchema: [String: AnyCodable]

        /// Creates a catalog tool entry.
        public init(name: String, description: String?, inputSchema: [String: AnyCodable]) {
            self.name = name
            self.description = description
            self.inputSchema = inputSchema
        }

        enum CodingKeys: String, CodingKey {
            case name, description, inputSchema
        }

        /// Canonical encoding: keys sorted (description < inputSchema <
        /// name), the schema recursively sorted.
        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encodeIfPresent(description, forKey: .description)
            try container.encode(CanonicalJSON(inputSchema), forKey: .inputSchema)
            try container.encode(name, forKey: .name)
        }
    }

    /// The binary's name (matching the session server identity).
    public let name: String
    /// The binary's version.
    public let version: String
    /// The binary's description, when it has one.
    public let description: String?
    /// The tool surface, dispatcher-first.
    public let tools: [Tool]

    /// Creates a catalog.
    public init(name: String, version: String, description: String?, tools: [Tool]) {
        self.name = name
        self.version = version
        self.description = description
        self.tools = tools
    }

    enum CodingKeys: String, CodingKey {
        case name, version, description, tools
    }

    /// Canonical encoding: keys sorted (description < name < tools < version).
    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(name, forKey: .name)
        try container.encode(tools, forKey: .tools)
        try container.encode(version, forKey: .version)
    }

    /// Discovers the compiled tool surface of a dispatcher.
    ///
    /// The catalog is read at the root access level — it describes what the
    /// binary is compiled to serve; per-caller access filtering applies to
    /// live `tools/call` invocations, not to the binary's self-description.
    ///
    /// - Parameters:
    ///   - name: The binary's name.
    ///   - version: The binary's version.
    ///   - description: The binary's description. An empty string yields `nil`.
    ///   - dispatcher: The compile-time-known dispatch surface
    ///     (macro-generated by `MCPApplication`).
    ///   - additionalTools: Extra tools to include after the dispatcher's,
    ///     registered as instances so constructor configuration survives.
    /// - Returns: The catalog, tools in catalog order (dispatcher-first).
    public static func discover(
        name: String,
        version: String,
        description: String = "",
        dispatcher: some MCPToolDispatcher,
        additionalTools: [any MCPTool] = []
    ) -> MCPToolCatalog {
        // quiet by default: introspection runs inside a tool binary whose
        // stderr is a diagnostics channel, not a log sink.
        var logger = Logger(label: "mcp.catalog")
        logger.logLevel = .critical

        let router = MCPMessageRouter(name: name, version: version, logger: logger, dispatcher: dispatcher)
        for tool in additionalTools {
            router.registerInstance(type(of: tool).toolName, instance: tool)
        }

        let definitions = router.catalog(for: MCPCallerInfo(sourceAddress: nil, accessLevel: .root))
        let tools = definitions.map { definition in
            Tool(name: definition.name, description: definition.description, inputSchema: definition.inputSchema)
        }
        return MCPToolCatalog(
            name: name,
            version: version,
            description: description.isEmpty ? nil : description,
            tools: tools
        )
    }
}

// MARK: - Canonical JSON

/// A JSON value tree that encodes with object keys sorted at every depth.
///
/// The framework's encoders are position-based: they write object keys in
/// call order, and Swift dictionaries iterate in per-process hash order — so
/// encoding a dictionary-shaped tree directly is not byte-stable across runs.
/// This wrapper carries the tree in a canonical (sorted-key) form and emits
/// it in that order, which is what makes catalogs and manifests deterministic.
enum CanonicalJSON: Encodable {
    indirect case object([(key: String, value: CanonicalJSON)])
    case array([CanonicalJSON])
    case scalar(AnyCodable)

    /// Wraps an arbitrary JSON-shaped value, canonicalizing recursively.
    ///
    /// `[String: Any]`, `[String: AnyCodable]`, `[Any]`, `AnyCodable`, and
    /// plain JSON scalars are all understood; anything else falls back to
    /// ``AnyCodable``'s own encoding rules.
    init(_ value: Any) {
        switch value {
        case let codable as AnyCodable:
            self.init(codable.value)
        case let object as [String: AnyCodable]:
            self = .object(object.map { (key: $0.key, value: CanonicalJSON($0.value)) })
        case let object as [String: Any]:
            self = .object(object.map { (key: $0.key, value: CanonicalJSON($0.value)) })
        case let array as [Any]:
            self = .array(array.map { CanonicalJSON($0) })
        default:
            self = .scalar(AnyCodable(value))
        }
    }

    func encode(to encoder: any Encoder) throws {
        switch self {
        case .object(let entries):
            var container = encoder.container(keyedBy: DynamicCodingKey.self)
            for entry in entries.sorted(by: { $0.key < $1.key }) {
                try container.encode(entry.value, forKey: DynamicCodingKey(entry.key))
            }
        case .array(let items):
            var container = encoder.unkeyedContainer()
            for item in items {
                try container.encode(item)
            }
        case .scalar(let value):
            var container = encoder.singleValueContainer()
            try container.encode(value)
        }
    }
}